# This workflow assists with initial triage of new issues by applying
# labels based on data provided in the issue.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
#
# - Patina DevOps Repo: https://github.com/OpenDevicePartnership/patina-devops
# - File Sync Settings: https://github.com/OpenDevicePartnership/patina-devops/blob/main/.sync/Files.yml
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##
name: Initial Triage for New Issue

on:
  issues:
    types: [ opened ]

jobs:
  triage:
    permissions:
      contents: read
      issues: write

    uses: OpenDevicePartnership/patina-devops/.github/workflows/IssueTriager.yml@v0.3.4
    secrets: inherit
